version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "github.com/expr-lang/expr"
        dependency-type: "indirect"
    open-pull-requests-limit: 5
